commands_dict = {
    'help': {'ru': 'Информация о командах', 'en': 'Information about commands'},
    'init': {'ru': 'Создание репозитория', 'en': 'Creating a repository'},
    'remove': {'ru': 'Удаление репозитория', 'en': 'Deleting a repository'},
    'commit': {'ru': 'Создание коммита', 'en': 'Commit creation'},
    'rollback': {'ru': 'Откат к коммиту', 'en': 'Rollback to a commit'},
    'hist': {'ru': 'История коммитов', 'en': 'Commit history'},
    'status': {'ru': 'Статус репозитория (отображает изменения)', 'en': 'Repository status'},
    'tree': {'ru': 'Вывод структуры файлов репозитория', 'en': 'Print repository files structure'},
    'lang': {'ru': 'Выбор языка', 'en': 'Language selection'},
    'crypt': {'ru': 'Зашифровать репозиторий', 'en': 'Encrypt repositary'},
    'decrypt': {'ru': 'Расшифровать репозиторий', 'en': 'Decrypt repositary'},
}

phrase = {
    'Основные команды': {'ru': 'Основные команды', 'en': 'Base commands'},
    'Пример': {'ru': 'Пример', 'en': 'Example'},
    'команда': {'ru': 'команда', 'en': 'command'},
    'аргументы': {'ru': 'аргументы', 'en': 'arguments'},
    'Укажите команду для выполнения': {'ru': 'Укажите команду для выполнения', 'en': 'Specify the command to execute'},
    'не является командой': {'ru': 'не является командой', 'en': 'not is command'},
    'Чтобы получить справку, введите': {'ru': 'Чтобы получить справку, введите', 'en': 'To get help, enter'},
    'Репозиторий уже создан в': {'ru': 'Репозиторий уже создан в', 'en': 'The repository has already been created in'},
    'Чтобы создать новый, сначала удалите старый': {'ru': 'Чтобы создать новый, сначала удалите старый', 'en': 'To create a new one, first delete the old one'},
    'Создан репозиторий в': {'ru': 'Создан репозиторий в', 'en': 'Repositary created in'},
    'Репозиторий еще не создан': {'ru': 'Репозиторий еще не создан', 'en': 'The repository has not yet been created'},
    'Репозиторий удален': {'ru': 'Репозиторий удален', 'en': 'Repositary deleted'},
    'Укажите хэш коммита к которому нужно вернуться': {'ru': 'Укажите хэш коммита к которому нужно вернуться', 'en': 'Specify the hash of the commit you want to rollback to'},
    'хэш': {'ru': 'хэш', 'en': 'hash'},
    'путь': {'ru': 'путь', 'en': 'path'},
    'Укажите используемый язык': {'ru': 'Укажите используемый язык', 'en': 'Specify the language used'},
    'Указан неверный язык': {'ru': 'Указан неверный язык', 'en': 'Invalid language specified'},
    'Сохранен коммит': {'ru': 'Сохранен коммит', 'en': 'Commit saved'},
    'Коммит не создан. Нет изменений': {'ru': 'Коммит не создан. Нет изменений', 'en': 'The commit was not created. No changes'},
    'Нет коммита': {'ru': 'Нет коммита', 'en': 'No such commit'},
    'Не найдено для удаления': {'ru': 'Не найдено для удаления', 'en': 'Not found to delete'},
    'История коммитов': {'ru': 'История коммитов', 'en': 'Commit history'},
    'Коммитов еще не было': {'ru': 'Коммитов еще не было', 'en': 'There have been no commits yet'},
    'Изменений нет': {'ru': 'Изменений нет', 'en': 'No any changes'},
    'История коммитов пуста': {'ru': 'История коммитов пуста', 'en': 'Commit history is empty'},
    'Репозиторий зашифрован, ключ': {'ru': 'Репозиторий зашифрован, ключ', 'en': 'The repository is encrypted, key'},
    'Нужно указать ключ шифрования или добавить файл с ключом key': {'ru': 'Нужно указать ключ шифрования или добавить файл с ключом key', 'en': 'You need to specify the encryption key or add a file with the key'},
    'Репозиторий расшифрован': {'ru': 'Репозиторий расшифрован', 'en': 'The repository is decrypted'},
}